services:
  ollama-mcp-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - CORS_ORIGINS=*
    volumes:
      - ./mcp-config.json:/root/mcp-config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: uv run ollama-mcp-bridge --ollama-url=${OLLAMA_URL:-http://host.docker.internal:11434}
