name: Release Dry Run

on:
  push:
    tags:
      - 'v*-rc*'  # Matches release candidates like v0.2.0-rc1
      - 'v*-beta*'
      - 'v*-alpha*'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.10

      - name: Install build dependencies
        run: uv pip install build twine

      - name: Build package
        run: uv run python -m build

      - name: Check package
        run: uv run twine check dist/*

      - name: Verify version matches tag
        run: |
          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          PKG_VERSION=$(uv run python -c "import setuptools_scm; print(setuptools_scm.get_version())")
          echo "Tag version: $TAG_VERSION"
          echo "Package version: $PKG_VERSION"
          if [[ "$PKG_VERSION" != *"$TAG_VERSION"* ]]; then
            echo "Version mismatch between tag and package!"
            exit 1
          fi

      # Upload the built packages as artifacts for inspection
      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
