name: TestPyPI Publish

on:
  push:
    tags:
      - 'v*a*'   # Trigger on alpha releases like v0.3.0a1
      - 'v*b*'   # Trigger on beta releases like v0.3.0b1
      - 'v*rc*'  # Trigger on release candidates like v0.3.0rc1
    branches:
      - fix/build-system-and-ci # this is temporary branch for testing the build system and CI

jobs:
  test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
