# This workflow publishes the package to TestPyPI when a tag is pushed.
name: Test Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]' # Matches semantic versioning tags like v1.0.0
    branches:
      - fix/build-system-and-ci # Temporary branch for testing
jobs:
  test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: testpypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Install from TestPyPI no-deps
        run: pip install --index-url https://test.pypi.org/simple/ --no-deps ollama-mcp-bridge
      - name: Check version
        run: ollama-mcp-bridge --version
