name: Tests

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.png'
      - 'LICENSE'
      - 'misc/**'
      - '**/*.txt'
      - '.gitignore'
      - '.python-version'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - '**/*.gif'
      - '**/*.png'
      - 'LICENSE'
      - 'misc/**'
      - '**/*.txt'
      - '.gitignore'
      - '.python-version'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important for setuptools_scm to work correctly

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.10

    - name: Install dependencies
      run: |
        uv sync --extra test

    - name: Run unit tests
      run: |
        uv run pytest tests/test_unit.py -v

    - name: Test imports and basic functionality
      run: |
        uv run python -c "from src.ollama_mcp_bridge.mcp_manager import MCPManager; print('✓ MCPManager import works')"
        uv run python -c "from src.ollama_mcp_bridge.api import app; print('✓ FastAPI app import works')"

    - name: Test version detection
      run: |
        uv pip install -e .
        uv run python -c "from ollama_mcp_bridge import __version__; print(f'Detected version: {__version__}')"
